<a href="https://colab.research.google.com/github/Ravravan/pytorch/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IMPORT MNIST

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import  make_grid
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
%matplotlib inline




In [4]:
# converts MNIST images into a tensor of 4-D
transform = transforms.ToTensor()

In [6]:
#train data
train_data = datasets.MNIST(root='/cnn_data', train=True, download = True, transform=transform)

In [7]:
#test data
test_data = datasets.MNIST(root='/cnn_data', train=False, download = True, transform=transform)

In [8]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: /cnn_data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [9]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: /cnn_data
    Split: Test
    StandardTransform
Transform: ToTensor()

#Convolutional and pooling layers

In [19]:
#create a small batch size for images..
train_loader= DataLoader(train_data, batch_size=10, shuffle= True   )
test_loader= DataLoader(test_data, batch_size=10, shuffle= False  )

In [21]:
#define CNN model
conv1 = nn.Conv2d(1, 6, 3, 1)
conv2 = nn.Conv2d(6, 16, 3, 1)

In [23]:
#grab 1 MNIST record/image
for i, (x_train, y_train) in enumerate(train_data):
  break

In [24]:
x_train

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [26]:
x_train.shape


torch.Size([1, 28, 28])

In [28]:
x = x_train.view([1,1,28,28])

In [29]:
#perform our 1st convolution
x = F.relu(conv1(x)) # rectified linear unit for our activation function..

In [30]:
x

tensor([[[[0.0942, 0.0942, 0.0942,  ..., 0.0942, 0.0942, 0.0942],
          [0.0942, 0.0942, 0.0942,  ..., 0.0942, 0.0942, 0.0942],
          [0.0942, 0.0942, 0.0942,  ..., 0.0942, 0.0942, 0.0942],
          ...,
          [0.0942, 0.0942, 0.0307,  ..., 0.0942, 0.0942, 0.0942],
          [0.0942, 0.0942, 0.0384,  ..., 0.0942, 0.0942, 0.0942],
          [0.0942, 0.0942, 0.0942,  ..., 0.0942, 0.0942, 0.0942]],

         [[0.2335, 0.2335, 0.2335,  ..., 0.2335, 0.2335, 0.2335],
          [0.2335, 0.2335, 0.2335,  ..., 0.2335, 0.2335, 0.2335],
          [0.2335, 0.2335, 0.2335,  ..., 0.2335, 0.2335, 0.2335],
          ...,
          [0.2335, 0.2335, 0.1323,  ..., 0.2335, 0.2335, 0.2335],
          [0.2335, 0.2335, 0.2491,  ..., 0.2335, 0.2335, 0.2335],
          [0.2335, 0.2335, 0.2335,  ..., 0.2335, 0.2335, 0.2335]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

In [31]:
x.shape # lose  of 2pixels due to the padding..

torch.Size([1, 6, 26, 26])

In [34]:
 # pooling layer
x= F.max_pool2d(x, 2, 2)

In [35]:
x.shape

torch.Size([1, 6, 13, 13])

In [36]:
#do our second convolutional layer
x= F.relu(conv2(x))

In [37]:
x

tensor([[[[0.1492, 0.1688, 0.1178,  ..., 0.0801, 0.1201, 0.0761],
          [0.1503, 0.1344, 0.0605,  ..., 0.0778, 0.1722, 0.0905],
          [0.1370, 0.0491, 0.0582,  ..., 0.1290, 0.2318, 0.1769],
          ...,
          [0.1470, 0.1289, 0.1284,  ..., 0.1485, 0.1438, 0.1464],
          [0.0211, 0.0084, 0.0000,  ..., 0.1809, 0.1307, 0.1426],
          [0.0571, 0.1261, 0.0796,  ..., 0.1297, 0.1445, 0.1425]],

         [[0.0272, 0.0479, 0.0705,  ..., 0.0717, 0.0148, 0.0527],
          [0.0215, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0103],
          [0.0308, 0.1406, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0569, 0.0404, 0.0174,  ..., 0.1001, 0.0000, 0.0286],
          [0.0070, 0.0000, 0.0000,  ..., 0.0422, 0.0000, 0.0249],
          [0.1002, 0.0207, 0.0000,  ..., 0.0000, 0.0293, 0.0248]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0346, 0.0509, 0.0000],
          [0.0000, 0.0000, 0.0380,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0149,  ..., 0

In [38]:
x.shape # same here lose 2 pixels beacuse of the padding.We did not set any padding..

torch.Size([1, 16, 11, 11])

In [39]:
#pooling layer
x=F.max_pool2d(x,2,2)

In [40]:
x.shape

torch.Size([1, 16, 5, 5])

#MODEL

In [42]:
#model class
class convolutionalNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1,6,3,1)
    self.conv2 = nn.Conv2d(6,16,3,1)

    #full connected layer
    self.fc1 =nn.Linear(5*5*16, 120)
    self.fc2 =nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    x= F.relu(self.conv1(x))
    x=F.max_pool2d(x,2,2)
    #second pass
    x= F.relu(self.conv2(x))
    x=F.max_pool2d(x,2,2)

    #re-view to flatten it out
    x = x.view(-1, 16*5*5)


    #fully connected layer

    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x=self.fc3(x)

    return F.log_softmax(x, dim=1)

In [43]:
#create an instance of our model
torch.manual_seed(41)
model = convolutionalNetwork()
model

convolutionalNetwork(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [44]:
#loss function optimizer

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)