<a href="https://colab.research.google.com/github/Ravravan/pytorch/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IMPORT MNIST

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import  make_grid
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
%matplotlib inline




In [2]:
# converts MNIST images into a tensor of 4-D
transform = transforms.ToTensor()

In [3]:
#train data
train_data = datasets.MNIST(root='/cnn_data', train=True, download = True, transform=transform)

100%|██████████| 9.91M/9.91M [00:00<00:00, 19.3MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 498kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.56MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 13.9MB/s]


In [4]:
#test data
test_data = datasets.MNIST(root='/cnn_data', train=False, download = True, transform=transform)

In [5]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: /cnn_data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [6]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: /cnn_data
    Split: Test
    StandardTransform
Transform: ToTensor()

#Convolutional and pooling layers

In [7]:
#create a small batch size for images..
train_loader= DataLoader(train_data, batch_size=10, shuffle= True   )
test_loader= DataLoader(test_data, batch_size=10, shuffle= False  )

In [8]:
#define CNN model
conv1 = nn.Conv2d(1, 6, 3, 1)
conv2 = nn.Conv2d(6, 16, 3, 1)

In [9]:
#grab 1 MNIST record/image
for i, (x_train, y_train) in enumerate(train_data):
  break

In [10]:
x_train

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [11]:
x_train.shape


torch.Size([1, 28, 28])

In [12]:
x = x_train.view([1,1,28,28])

In [13]:
#perform our 1st convolution
x = F.relu(conv1(x)) # rectified linear unit for our activation function..

In [14]:
x

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0664, 0.0664, 0.0664,  ..., 0.0664, 0.0664, 0.0664],
          [0.0664, 0.0664, 0.0664,  ..., 0.0664, 0.0664, 0.0664],
          [0.0664, 0.0664, 0.0664,  ..., 0.0664, 0.0664, 0.0664],
          ...,
          [0.0664, 0.0664, 0.0000,  ..., 0.0664, 0.0664, 0.0664],
          [0.0664, 0.0664, 0.0000,  ..., 0.0664, 0.0664, 0.0664],
          [0.0664, 0.0664, 0.0664,  ..., 0.0664, 0.0664, 0.0664]],

         [[0.0541, 0.0541, 0.0541,  ..., 0.0541, 0.0541, 0.0541],
          [0.0541, 0.0541, 0.0541,  ..., 0.0541, 0.0541, 0.0541],
          [0.0541, 0.0541, 0.0541,  ..., 0

In [15]:
x.shape # lose  of 2pixels due to the padding..

torch.Size([1, 6, 26, 26])

In [16]:
 # pooling layer
x= F.max_pool2d(x, 2, 2)

In [17]:
x.shape

torch.Size([1, 6, 13, 13])

In [18]:
#do our second convolutional layer
x= F.relu(conv2(x))

In [19]:
x

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0098, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0287, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.1441, 0.1485, 0.1311,  ..., 0.0000, 0.0000, 0.0797],
          [0.1491, 0.1139, 0.0620,  ..., 0.2063, 0.1489, 0.0771],
          [0.1494, 0.1492, 0.1705,  ..., 0.2625, 0.1886, 0.0840],
          ...,
          [0.1545, 0.1041, 0.0590,  ..., 0.1360, 0.1595, 0.1474],
          [0.1197, 0.0532, 0.0000,  ..., 0.1366, 0.1008, 0.1436],
          [0.1814, 0.1155, 0.1614,  ..., 0.1883, 0.1479, 0.1435]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0806,  ..., 0

In [20]:
x.shape # same here lose 2 pixels beacuse of the padding.We did not set any padding..

torch.Size([1, 16, 11, 11])

In [21]:
#pooling layer
x=F.max_pool2d(x,2,2)

In [22]:
x.shape

torch.Size([1, 16, 5, 5])

#MODEL

In [23]:
#model class
class convolutionalNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1,6,3,1)
    self.conv2 = nn.Conv2d(6,16,3,1)

    #full connected layer
    self.fc1 =nn.Linear(5*5*16, 120)
    self.fc2 =nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    x= F.relu(self.conv1(x))
    x=F.max_pool2d(x,2,2)
    #second pass
    x= F.relu(self.conv2(x))
    x=F.max_pool2d(x,2,2)

    #re-view to flatten it out
    x = x.view(-1, 16*5*5)


    #fully connected layer

    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x=self.fc3(x)

    return F.log_softmax(x, dim=1)

In [24]:
#create an instance of our model
torch.manual_seed(41)
model = convolutionalNetwork()
model

convolutionalNetwork(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [25]:
#loss function optimizer

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

#TRAIN AND TEST

In [29]:
import time
start_time = time.time()

#create variable to tracks things
epochs = 5
train_losses =[]
test_losses = []
train_correct = []
test_correct = []

#foor loop of epochs

for i in  range(epochs):
  trn_corr = 0
  tst_corr = 0


  #train

  for b,(x_train, y_train ) in enumerate(train_loader):
    b+=1
    y_pred  = model(x_train)
    loss = criterion(y_pred, y_train)

    predicted = torch.max(y_pred.data, 1)[1]
    batch_corr = (predicted == y_train).sum()
    trn_corr += batch_corr

#update our parameters
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


    #print out some results


    if b%600 ==0:
      print(f'Epoch:{i}  Batch:{b} Loss:{loss.item()}')

    train_losses.append(loss)
    train_correct.append(trn_corr)



 #test

  with torch.no_grad():
   for b,(x_test, y_test) in enumerate(test_loader):
    y_val = model(x_test)
    predited = torch.max(y_val.data, 1)[1]
    tst_corr += (predicted == y_test).sum()
    loss = criterion(y_val, y_test)
    test_losses.append(loss)
    test_correct.append(tst_corr)



current_time = time.time()
total = current_time - start_time
print(f'Training took: {total/60} min!')


Epoch:0  Batch:600 Loss:0.07732944935560226
Epoch:0  Batch:1200 Loss:0.05652786046266556
Epoch:0  Batch:1800 Loss:0.02247507870197296
Epoch:0  Batch:2400 Loss:0.15841881930828094
Epoch:0  Batch:3000 Loss:0.0016886095982044935
Epoch:0  Batch:3600 Loss:0.010358510538935661
Epoch:0  Batch:4200 Loss:0.20619675517082214
Epoch:0  Batch:4800 Loss:0.01819475181400776
Epoch:0  Batch:5400 Loss:0.0017014555633068085
Epoch:0  Batch:6000 Loss:0.00753634562715888
Epoch:1  Batch:600 Loss:0.2971245050430298
Epoch:1  Batch:1200 Loss:0.021411366760730743
Epoch:1  Batch:1800 Loss:0.15131793916225433
Epoch:1  Batch:2400 Loss:0.10626612603664398
Epoch:1  Batch:3000 Loss:0.07575374096632004
Epoch:1  Batch:3600 Loss:0.0002335333701921627
Epoch:1  Batch:4200 Loss:0.0002180782175855711
Epoch:1  Batch:4800 Loss:0.0002955275122076273
Epoch:1  Batch:5400 Loss:0.004222441464662552
Epoch:1  Batch:6000 Loss:0.0004894716548733413
Epoch:2  Batch:600 Loss:0.12864477932453156
Epoch:2  Batch:1200 Loss:0.00466859247535467