<a href="https://colab.research.google.com/github/Ravravan/pytorch/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
#Reshape if we don't know the shape of the items using -1
my_torch2 =torch.arange(15)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [10]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
#with reshape and view, they will update.

my_torch4[1] = 7
my_torch4

tensor([[0, 1, 2, 3, 4],
        [7, 7, 7, 7, 7]])

In [14]:
my_torch3[0] = 1
my_torch3

tensor([1, 1, 2, 3, 4, 7, 7, 7, 7, 7])

In [15]:
#slices
my_torch5 = torch.arange(10)
my_torch5


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#grab a specific item
my_torch5[8]

tensor(8)

In [17]:
#grab slice
my_torch6 = my_torch5.reshape(5,2)
my_torch6


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
my_torch6[:, 1]

tensor([1, 3, 5, 7, 9])

In [20]:
#return column
my_torch6[:,1:]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])