<a href="https://colab.research.google.com/github/Ravravan/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np

np1 = np.random.rand(3,4)
np1


array([[0.5520748 , 0.86412281, 0.19593602, 0.71217816],
       [0.76701316, 0.21074244, 0.52881134, 0.40794703],
       [0.59726528, 0.2595257 , 0.07464108, 0.26107054]])

#TENSORS

In [5]:
tensor_2D = torch.randn(3,4)
tensor_2D

tensor([[-0.9689,  0.2808,  0.2034, -0.5605],
        [-0.8531, -0.5308,  0.1095,  0.2822],
        [-1.4424,  1.0361, -0.9302,  2.3092]])

In [6]:
tensor_3D = torch.zeros(2,3,4)
tensor_3D

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## creat tensor out of numpy array

In [11]:
m_tensor = torch.tensor(np1)
m_tensor

tensor([[0.5521, 0.8641, 0.1959, 0.7122],
        [0.7670, 0.2107, 0.5288, 0.4079],
        [0.5973, 0.2595, 0.0746, 0.2611]], dtype=torch.float64)