<a href="https://colab.research.google.com/github/Ravravan/pytorch/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch


#TENSOR MATH OPERASTIONS

In [23]:
#Addition
tensor_a = torch.tensor([1,2,3,4,5,6,9])
tensor_b = torch.tensor([4,5,8,2,1,7,3])


tensor_a + tensor_b


tensor([ 5,  7, 11,  6,  6, 13, 12])

In [24]:
#Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 5,  7, 11,  6,  6, 13, 12])

In [25]:
#Substrsction
tensor_b - tensor_a

tensor([ 3,  3,  5, -2, -4,  1, -6])

In [26]:
#Sub Function
torch.sub(tensor_a, tensor_b)

tensor([-3, -3, -5,  2,  4, -1,  6])

In [27]:
#Multiplication
tensor_a * tensor_b

tensor([ 4, 10, 24,  8,  5, 42, 27])

In [28]:
#Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 4, 10, 24,  8,  5, 42, 27])

In [29]:
#Division
tensor_b / tensor_a

tensor([4.0000, 2.5000, 2.6667, 0.5000, 0.2000, 1.1667, 0.3333])

In [30]:
#Div longhand
torch.div(tensor_a, tensor_b)

tensor([0.2500, 0.4000, 0.3750, 2.0000, 5.0000, 0.8571, 3.0000])

In [32]:
#Remainder Moduls
tensor_b % tensor_a

tensor([0, 1, 2, 2, 1, 1, 3])

In [33]:
#Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 2, 1, 1, 3])

In [34]:
#Exponents
tensor_a ** tensor_b

tensor([     1,     32,   6561,     16,      5, 279936,    729])

In [35]:
#Exponents longhand
torch.pow(tensor_b, tensor_a)

tensor([     4,     25,    512,     16,      1, 117649,  19683])

In [36]:
#Reassigment_
tensor_a.add_(tensor_b)

tensor([ 5,  7, 11,  6,  6, 13, 12])

In [37]:
tensor_a

tensor([ 5,  7, 11,  6,  6, 13, 12])